'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { validatePiResourceSettings, loadPiResources, buildPiResourcePrompt, parseCommandArgs, substituteArgs, expandPromptTemplate } = require('../dist/pi-resources.cjs');
const root = path.resolve(__dirname, '..', '.test-tmp');
fs.mkdirSync(root, { recursive: true });
const temporary = fs.mkdtempSync(path.join(root, 'pi-resources-'));
const ancestor = path.join(temporary, 'ancestor');
const workspace = path.join(ancestor, 'workspace');
const globalDir = path.join(temporary, 'global-agent');
const extra = path.join(temporary, 'extra');
function write(relative, text) {
  const file = path.join(temporary, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text); return file;
}
write('global-agent/AGENTS.md', 'GLOBAL_CONTEXT');
write('global-agent/CLAUDE.md', 'IGNORED_GLOBAL_CLAUDE');
write('ancestor/AGENTS.md', 'ANCESTOR_CONTEXT');
write('ancestor/CLAUDE.md', 'IGNORED_ANCESTOR_CLAUDE');
write('ancestor/workspace/CLAUDE.md', 'WORKSPACE_CONTEXT');
write('ancestor/workspace/child/AGENTS.md', 'IGNORED_DESCENDANT');
write('global-agent/SYSTEM.md', 'GLOBAL_SYSTEM');
write('global-agent/APPEND_SYSTEM.md', 'GLOBAL_APPEND');
write('ancestor/workspace/.pi/SYSTEM.md', 'PROJECT_SYSTEM');
write('ancestor/workspace/.pi/APPEND_SYSTEM.md', 'PROJECT_APPEND');
write('global-agent/prompts/review.md', '---\ndescription: Global review\n---\nGlobal $1');
write('ancestor/workspace/.pi/prompts/review.md', 'Project collision $1');
write('ancestor/workspace/.pi/prompts/args.md', '---\ndescription: >\n  Review the\n  quoted arguments\n---\nFirst=$1; second=$2; all=$@; tail=${@:2}; two=${@:1:2}');
write('ancestor/workspace/.pi/prompts/fallback.md', '\n' + 'x'.repeat(70) + '\nMore');
write('ancestor/workspace/.pi/prompts/nested/hidden.md', 'Not discovered recursively');
write('extra/explicit.md', "---\ndescription: 'Explicit user''s prompt'\n---\nExplicit $ARGUMENTS");
write('extra/deep/more.md', 'Additional directory $1');
write('extra/binary.md', Buffer.from([0, 255]));

const settings = validatePiResourceSettings({ agentDir: globalDir, promptPaths: [path.join(extra, 'explicit.md'), path.join(extra, 'deep'), path.join(extra, 'binary.md')] });
assert.strictEqual(settings.enabled, true);
assert.strictEqual(settings.includeAncestors, true);
for (const input of [{ agentDir: 'relative' }, { agentDir: '~/.pi/agent' }, { promptPaths: ['relative.md'] }, { enabled: 'true' }, { includeAncestors: 1 }, { promptPaths: null }]) assert.throws(() => validatePiResourceSettings(input));
const updated = validatePiResourceSettings({ enabled: false }, settings);
assert.strictEqual(updated.agentDir, globalDir);
assert.notStrictEqual(updated.promptPaths, settings.promptPaths);
const resources = loadPiResources(workspace, settings);
const ownContexts = resources.contextFiles.filter(item => item.path.startsWith(temporary));
assert.deepStrictEqual(ownContexts.map(item => item.content), ['GLOBAL_CONTEXT', 'ANCESTOR_CONTEXT', 'WORKSPACE_CONTEXT']);
assert.strictEqual(resources.systemPrompt, 'PROJECT_SYSTEM');
assert.strictEqual(resources.appendSystemPrompt, 'PROJECT_APPEND');
assert.strictEqual(path.basename(resources.systemPromptPath), 'SYSTEM.md');
assert.deepStrictEqual(resources.prompts.map(item => item.name), ['review', 'args', 'fallback', 'explicit', 'more']);
assert(resources.warnings.some(item => item.includes('collision')));
assert(resources.warnings.some(item => item.includes('binary')));
assert(resources.prompts.find(item => item.name === 'args').description.includes('Review the quoted arguments'));
assert(resources.prompts.find(item => item.name === 'fallback').description.startsWith('x'.repeat(60) + '...'));
assert.strictEqual(resources.prompts.find(item => item.name === 'explicit').content, 'Explicit $ARGUMENTS');
assert.strictEqual(expandPromptTemplate('/review test', resources.prompts), 'Global test');
assert.strictEqual(expandPromptTemplate('/args first "two words" third', resources.prompts), 'First=first; second=two words; all=first two words third; tail=two words third; two=first two words');
assert.strictEqual(expandPromptTemplate('/args\tfirst', resources.prompts).split(';')[0], 'First=first');
assert.strictEqual(expandPromptTemplate('/missing value', resources.prompts), '/missing value');
assert.strictEqual(expandPromptTemplate('normal task', resources.prompts), 'normal task');
assert.deepStrictEqual(parseCommandArgs('one "two words" \'three words\' C:\\project\\file ""'), ['one', 'two words', 'three words', 'C:\\project\\file']);
assert.strictEqual(substituteArgs('$1 | $2 | $@ | $ARGUMENTS | ${@:2:1}', ['$@', '$1']), '$@ | $1 | $@ $1 | $@ $1 | $1');
assert.strictEqual(substituteArgs('${@:0:1} ${@:2:0} $99', ['a', 'b']), 'a  ');
assert.throws(() => substituteArgs('$1'.repeat(1000), ['x'.repeat(1000)]), /256 KiB/);
const prompt = buildPiResourcePrompt('DEFAULT_PROMPT', resources);
assert(prompt.startsWith('PROJECT_SYSTEM\n\nPROJECT_APPEND'));
assert(!prompt.includes('DEFAULT_PROMPT'));
assert(prompt.includes('# Project Context\n\nProject-specific instructions and guidelines:'));
assert(prompt.indexOf('GLOBAL_CONTEXT') < prompt.indexOf('ANCESTOR_CONTEXT'));
assert(!prompt.includes('IGNORED_'));
const defaultGlobal = loadPiResources(workspace, { includeAncestors: false });
assert.deepStrictEqual(defaultGlobal.contextFiles.map(item => item.content), ['WORKSPACE_CONTEXT']);
assert(!defaultGlobal.prompts.some(item => item.source === 'user'));
const disabled = loadPiResources(workspace, { enabled: false, agentDir: globalDir });
assert.strictEqual(disabled.contextFiles.length, 0);
assert.strictEqual(disabled.prompts.length, 0);
assert.strictEqual(disabled.systemPrompt, undefined);
assert.strictEqual(buildPiResourcePrompt('DEFAULT_PROMPT', disabled), 'DEFAULT_PROMPT');
assert.strictEqual(buildPiResourcePrompt('DEFAULT_PROMPT', Object.assign({}, disabled, { systemPrompt: '' })), 'DEFAULT_PROMPT');

const otherWorkspace = path.join(temporary, 'other-workspace');
fs.mkdirSync(otherWorkspace);
const globalOnly = loadPiResources(otherWorkspace, { agentDir: globalDir, includeAncestors: false });
assert.strictEqual(globalOnly.systemPrompt, 'GLOBAL_SYSTEM');
assert.strictEqual(globalOnly.appendSystemPrompt, 'GLOBAL_APPEND');
write('other-workspace/AGENTS.md', 'x'.repeat(128 * 1024 + 1));
write('other-workspace/CLAUDE.md', 'FALLBACK_AFTER_INVALID_AGENTS');
assert(loadPiResources(otherWorkspace, { includeAncestors: false }).warnings.some(item => item.includes('128 KiB')));
assert.strictEqual(loadPiResources(otherWorkspace, { includeAncestors: false }).contextFiles[0].content, 'FALLBACK_AFTER_INVALID_AGENTS');
try {
  fs.symlinkSync(globalDir, path.join(otherWorkspace, '.pi'), process.platform === 'win32' ? 'junction' : 'dir');
  const linked = loadPiResources(otherWorkspace, { includeAncestors: false });
  assert.strictEqual(linked.systemPrompt, undefined);
  assert.strictEqual(linked.prompts.length, 0);
  assert(linked.warnings.some(item => item.includes('outside')));
} catch (error) { if (!['EPERM', 'EACCES'].includes(error.code)) throw error; }
assert.strictEqual(fs.readFileSync(path.join(globalDir, 'SYSTEM.md'), 'utf8'), 'GLOBAL_SYSTEM');
console.log('PASS Pi context priority, explicit globals, SYSTEM/APPEND, prompt discovery/frontmatter/duplicates, slash arguments, literal substitution, limits and link containment.');
